---
title: Today I Learn
date: 2001-02-02
---

# Celery 환경변수 가져오지 못하는 오류

터미널에서 **celery -A project worker -l INFO** 를 통해 celery를 실행시키면

```if settings_dict['HOST'].startswith('/'):
AttributeError: 'NoneType' object has no attribute 'startswith'
```

db관련해서 이런 에러가 발생했다.

celery에서 환경변수 값을 제대로 가져오지 못하는 것 같았다. 왜냐하면
sqlite3에서는 잘 동작했지만 환경변수를 통해 세팅한 mysql이 동작하지 않았기 때문이다.
```python
DATABASES = {
    # 에러발생
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': os.environ.get("DB_NAME"),
        'USER': os.environ.get("DB_USER"),
        'PASSWORD': os.environ.get("DB_PASSWORD"),
        'HOST': os.environ.get("DB_HOST"),
        'PORT': os.environ.get("DB_PORT"),
        'OPTIONS': {
            'charset': 'utf8mb4',
        },
    },
    # 정상적으로 동작
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}
```

## 시도해본 것
celery.py에서 .env파일이 있는 경로에서 환경변수를 읽을 수 있도록 아래 코드를 추가 했지만 동일한 에러는 여전히 나타났다.
```python
dotenv.read_dotenv('./.env')
```

## 해결
터미널에서 아래와 같이 직접 환경변수를 셋팅하니 잘 동작하였다.
```
export DB_HOST=127.0.0.1
export DB_USER=
...
```

며칠 째 해결이 안되었는데 동작을 해서 기분이 좋았다.
export를 통해 수동으로 환경변수를 설정하지 않고 해결할 수 있는 방법을 찾아봐야겠다.

